#!/usr/bin/env bash

set -euo pipefail


RED="\033[0;31m"
YELLOW="\033[0;33m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
CYAN="\033[0;36m"
PURPLE="\033[0;35m"
NO_COLOR="\033[0m"


function install()
{
	FA_GIT_URL="https://github.com/P5vc/FetchApply.git"
	CRONTAB_ENTRY="$(( RANDOM % 60 )) $(( RANDOM % 24 )) * * *"

	echo -e "Welcome to the Fetch Apply installation script.\n\nPlease answer the following questions about how you would like to\ninstall Fetch Apply. If you are not sure what to put, press enter,\nand the default value in parentheses will be applied."

	echo -e "\n\n${BLUE}Where would you like to install Fetch Apply?\n${CYAN}Installation Path (/var/lib):${NO_COLOR}"
	read INSTALLATION_PATH
	if [ -z "$INSTALLATION_PATH" ]
	then
		INSTALLATION_PATH="/var/lib"
	fi

	if [ -e "${INSTALLATION_PATH}/fetchapply" ]
	then
		echo -e "${RED}Error. An existing Fetch Apply installation was found. Exiting...${NO_COLOR}"
		exit 1
	fi

	echo -e "\n\n${BLUE}Where would you like to create a log file?\n${CYAN}Log file (/var/log/fetchapply.log):${NO_COLOR}"
	read LOG_FILE_PATH
	if [ -z "$LOG_FILE_PATH" ]
	then
		LOG_FILE_PATH="/var/log/fetchapply.log"
	fi

	echo -e "\n\n${BLUE}What is your operations git URL?\n${CYAN}URL (https://github.com/P5vc/ServerConfigurations.git):${NO_COLOR}"
	read OPERATIONS_GIT_URL
	if [ -z "$OPERATIONS_GIT_URL" ]
	then
		OPERATIONS_GIT_URL="https://github.com/P5vc/ServerConfigurations.git"
	fi

	echo -e "\n\n${BLUE}What is the desired hostname for this server?\n${CYAN}Hostname (server):${NO_COLOR}"
	read SERVER_HOSTNAME
	if [ -z "$SERVER_HOSTNAME" ]
	then
		SERVER_HOSTNAME="server"
	fi

	echo -e "\n\n${BLUE}What is the desired Fetch Apply run frequency? The default is once every 24 hours.\n${CYAN}Run frequency in crontab syntax (${CRONTAB_ENTRY}):${NO_COLOR}"
	read THEIR_CRONTAB_ENTRY
	if [ -n "$THEIR_CRONTAB_ENTRY" ]
	then
		CRONTAB_ENTRY=$"THEIR_CRONTAB_ENTRY"
	fi

	if [ -z "$(/usr/bin/which git)" ]
	then
		echo -e "\n\n${YELLOW}Warning: git was not detected.\nAttempting to install git...${PURPLE}"
		apt-get update
		apt-get install git -y
		echo -e "${NO_COLOR}"
	else
		echo -e "\n\n${GREEN}Git detected...${NO_COLOR}"
	fi

	echo -e "\n\n${GREEN}Beginning installation...${PURPLE}"

	hostnamectl set-hostname $SERVER_HOSTNAME

	mkdir -p ${INSTALLATION_PATH}/fetchapply
	git clone $FA_GIT_URL ${INSTALLATION_PATH}/fetchapply
	ln -sf ${INSTALLATION_PATH}/fetchapply/fa /usr/bin/fa

	git clone $OPERATIONS_GIT_URL ${INSTALLATION_PATH}/fetchapply/operations

	echo "FA_ROOT=${INSTALLATION_PATH}/fetchapply" > /etc/fetchapply
	echo "LOG_FILE_PATH=${LOG_FILE_PATH}" >> /etc/fetchapply
	echo "OPERATIONS_GIT_URL=${OPERATIONS_GIT_URL}" >> /etc/fetchapply
	echo "MAX_LOG_LENGTH=10000" >> /etc/fetchapply

	if [ -e "/etc/cron.d/fa" ]
	then
		echo "$(cat /etc/cron.d/fa | grep -v ${INSTALLATION_PATH}/fetchapply)" > /etc/cron.d/fa
	fi
	echo -e "SHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\n${CRONTAB_ENTRY} root ${INSTALLATION_PATH}/fetchapply/fa 2>&1" >> /etc/cron.d/fa

	echo -e "\n\n${GREEN}Installation complete.${NO_COLOR}"
}

install
